name: release-node


on:
  push:
    branches:
      - master

    tags:
      - v[0-9]+.[0-9]+.[0-9]+


jobs:
  release-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        sample: ['01-in-memory']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x.x

      - name: Create package
        run: |
          cd "${{ matrix.sample }}/node"
          make package tag=${{ github.ref_name }}

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.sample }}/node/${{ matrix.sample }}-node-sample-${{ github.ref_name }}.zip
